name: Main

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - run: bazel --version
    - name: Test
      run: make test
