name: Main

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-latest, macos-12, macos-11 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: bazel --version
    - name: Test
      run: make test
